# Simple shell that performs 'cat' on a file, then pipes that into another file.
# Thus, it simulates a copy operation.

schema-version: "1.0.0"

meta:
  name: cat-cp
  version: "1.0.0"
  description: "Copies the contents of a source file to a target file."
  source:
    file: "script.ns"
    line: 1
    column: 1
  authors:
    - The Native Shell Team
  license:
    spdx-id: MIT

commands:
  default:
    source: { file: "script.ns" }
    thread: jt1
    # reuse the description from the meta section.
    definition:
      source: { file: "script.ns" }
      kind: macro
      macro: shell
      input:
        start_help:
          source: { file: "script.ns" }
          kind: string
          value: "Copy the contents of the SOURCE file into the TARGET file."
        parameters:
          source: { file: "script.ns" }
          kind: string-map-list
          value:
            - field: source
              kind: required
              source: parameter
              long-form: source
              short-form: s
              variable: SOURCE
              help: The path to the source file, whose contents will copy into TARGET.
            - field: target
              kind: required
              source: parameter
              long-form: target
              short-form: t
              variable: TARGET
              help: The path to the target file, which will store the contents from SOURCE.
            #- field: append
            #  kind: flag
            #  source: parameter
            #  long-form: append
            #  short-form: a
            #  help: Appends SOURCE to the end of TARGET; without this, the copy will replace the contents of TARGET.

threads:
  default:
    source: { file: "script.ns" }

    # Main thread starts the copy job thread.
    # It exits the script with an error if the copy job thread exits with an error.
    main:
      source: { file: "script.ns" }
      description: >
        Copy the SOURCE file to the TARGET file.  This will not create the
        directory containing the TARGET file.
      default: true
      parameters:
        - name: source
          aliases: [source, s]
          var-name: SOURCE
          description: >
            Path to the source file to copy.
          kind: string
        - name: target
          aliases: [target, t]
          var-name: TARGET
          description: >
            Path to the target file.
          kind: string
    steps:
      - name: main_s0
        source: { file: "script.ns" }
        run:
          kind: spawn-thread
          thread: jt1
      - name: main_s1
        source: { file: "script.ns" }
        run:
          kind: wait-for-thread
          thread: jt1
          exit-behavior:
            source: { file: "script.ns" }
            never-started:
              source: { file: "script.ns" }
              kind: abort-script
            default-behavior:
              # on-error - anything that isn't exit code 0.
              # Pass the error on to the user.
              source: { file: "script.ns" }
              kind: abort-script
            exit-code-behaviors:
              - source: { file: "script.ns" }
                min-code: 0
                max-code: 0
                behavior:
                  source: { file: "script.ns" }
                  kind: stop-script

  # The copy job web.
  # It first runs the job that prepares the streams for the jobs.
  # Then it runs the jobs async.
  # Then it waits for all the jobs to finish.
  jt1:
    source: { file: "script.ns" }
    steps:
      - name: jt1_j0x0_start
        source: { file: "script.ns" }
        run:
          kind: spawn-job
          job: j0x0
      - name: jt1_j0_stop
        source: { file: "script.ns" }
        run:
          kind: wait-for-job
          job: j0x0
          exit-behavior:
            source: { file: "script.ns" }
            never-started:
              source: { file: "script.ns" }
              kind: abort-script
            default-behavior:
              # on-error - anything that isn't exit code 0.
              # Pass the error on to the user.
              source: { file: "script.ns" }
              kind: stop-script
            exit-code-behaviors:
              # on-success - keep going.
              - source: { file: "script.ns" }
                min-code: 0
                max-code: 0
                behavior:
                  source: { file: "script.ns" }
                  kind: jump
                  by: 1
      - name: jt1_j1_start
        source: { file: "script.ns" }
        run:
          kind: spawn-job
          job: j0x1
      # There's just the one job to start, so, there you go.

      # Wait for all the launched jobs to stop.
      - name: jt1_stop
        source: { file: "script.ns" }
        run:
          # A script compiler can simplify this by just creating a wait-for-job,
          # but this is for testing.
          kind: wait-for-all
          jobs:
            - j0x1
          threads: []
          exit-behavior:
            source: { file: "script.ns" }
            never-started:
              source: { file: "script.ns" }
              kind: abort-script
            default-behavior:
              # on-error - anything that isn't exit code 0.
              # Pass the error on to the user.
              source: { file: "script.ns" }
              kind: stop-script
            exit-code-behaviors:
              # on-success - step ahead by 1 which, because this is
              # the last step in the thread, means end the thread.
              - source: { file: "script.ns" }
                min-code: 0
                max-code: 0
                behavior:
                  source: { file: "script.ns" }
                  kind: jump
                  by: 1

jobs:
  j0x0:
    # The first stream assembly job for the jobs in its tread's web.
    source: { file: "script.ns" }
    kind: stream
    streams:
      - source: { file: "script.ns" }
        from:
          # from the cat job.  cat uses a fd as the output.
          source: { file: "script.ns" }
          kind: fd
          job: j0x1
          fd: 0
        to:
          # pipe it directly into a file.
          source: { file: "script.ns" }
          kind: file
          filename:
            source: { file: "script.ns" }
            kind: lookup-string
            # 'default' references the thread named 'default', which
            # creates an implicit job that initializes before the thread starts.
            job: default
            name: target
  j0x1:
    # The cat module, which loads the source file and pipes it to the module's fd_0,
    # which the job j0x0 connected to the target file.
    source: { file: "script.ns" }
    kind: module
    module: cat
    initial-parameters: {}
    runtime-parameters:
      - source: { file: "script.ns" }
        name: filenames
        value:
          source: { file: "script.ns" }
          kind: constant-string-list
          value:
            - source: { file: "script.ns" }
              kind: lookup-string
              # 'default' references the thread named 'default', which
              # creates an implicit job that initializes before the thread starts.
              job: default
              name: source
