//SPDX:MIT

//! Keeps track of threads' state as they loop through their steps.

use super::mapvec::HashMapVec;
use std::collections::{HashMap, HashSet};

use crate::shell_lib::structure::{
    event::{Event, EventPayload, EventRef},
    job::{ExitCode, JobRef, ScriptExit},
    thread::{
        ExitBehavior, OnExitBehavior, ScheduleStep, StepCount, ThreadDescription, ThreadRef,
        ThreadStore,
    },
};

/// Requests to the run step for it to handle.  The caller may
/// have its own things it needs to handle with this.
pub struct Requests {
    /// Jobs that stopped their run function execution since the last invocation.
    jobs_ended: Vec<(JobRef, ScriptExit)>,

    /// Events produced by any job since the last invocation.
    new_events: Vec<Event>,
}

pub enum JobRunStatus {
    NotExist,
    NeverStarted,
    Running,
    Stopped(ScriptExit),
}

pub trait JobStatus {
    fn job_status(&self, job_ref: JobRef) -> JobRunStatus;
}

/// The condition of the thread step management after an incremental step.
pub enum LoopState {
    /// The main threads have all stopped.
    Stopped(ScriptExit),

    /// All threads are blocked waiting on a job to end or an event to trigger.
    Waiting,

    /// At least one thread has another step it can take.
    Active,
}

/// The state of the thread execution after the last call.
/// This includes whether it should wait for the next event rather than
/// running again for the next poll, and which behaviors the
/// caller should perform.
pub struct Response {
    /// The status of looping.
    pub state: LoopState,

    /// A collection of events generated by the threads during the evaluation step.
    pub generated_events: Vec<Event>,

    /// All jobs requested to start during the evaluation step.
    /// The caller still needs to obey the readiness state of the requested jobs to spawn.
    pub spawned_jobs: Vec<JobRef>,
}

/// Manage the incremental execution of each thread.
pub struct ThreadManager {
    // This passes the ThreadState object between the various collections
    // as the thread changes state.
    //
    // The memory can use some tightening, but it requires some strong tricks to get
    // it to work right.
    /// Ready for work.
    active: Vec<ThreadState>,

    /// Waiting for an event to happen.
    pending_event: HashMapVec<EventRef, ThreadState>,

    /// Waiting for a job to end.
    pending_job_end: HashMapVec<JobRef, ThreadState>,

    /// Waiting for a thread to end.
    pending_thread_end: HashMapVec<ThreadRef, ThreadState>,

    /// Waiting on jobs + threads to end.
    pending_join: Vec<WaitAccumulator>,

    /// Not currently running.
    stopped: HashMap<ThreadRef, ThreadState>,

    /// All the stopped main.
    main_complete: ErrCollector,
}

impl ThreadManager {
    /// Create a new manager.
    pub fn new(start_threads: Vec<ThreadRef>, store: ThreadStore) -> Result<Self, String> {
        let mut main = HashSet::new();
        for t_ref in start_threads {
            main.insert(t_ref);
        }
        let mut active = Vec::new();
        let mut stopped = HashMap::new();
        for t in store.drain() {
            if main.contains(&t.0) {
                active.push(ThreadState::new(t.0, t.1, true));
                main.remove(&t.0);
            } else {
                stopped.insert(t.0, ThreadState::new(t.0, t.1, false));
            }
        }
        if !main.is_empty() {
            Err(format!(
                "requested non-existent starting threads {:?}",
                main
            ))
        } else {
            Ok(ThreadManager {
                active,
                pending_event: HashMapVec::new(),
                pending_job_end: HashMapVec::new(),
                pending_thread_end: HashMapVec::new(),
                pending_join: Vec::new(),
                stopped,
                main_complete: ErrCollector::new(),
            })
        }
    }

    /// Run a step through all the threads.
    pub fn run_step<T: JobStatus>(
        &mut self,
        req: &Requests,
        job_status: T,
    ) -> Result<Response, String> {
        let mut run_state = AdvanceState::new();

        // First, update the pending state for all waiting-on items.
        // - events
        for event in &req.new_events {
            self.update_pending_events(&mut run_state, event)?;
        }
        // At this point, the pending events will still possibly be updated as
        // threads generate events.

        // - completed jobs
        for (job_ref, exit) in &req.jobs_ended {
            let mut jl = self.pending_job_end.handle(*job_ref);
            for t in jl.drain(0..jl.len()) {
                let (_w_ref, w_exit) = t.wait_for_job_step()?;
                #[cfg(test)]
                assert_eq!(*job_ref, _w_ref);

                self.handle_exit_behavior(t, &w_exit, &mut run_state, Some(exit));
            }
        }

        // Next, run a pass of stepping through all active threads.
        // Keep track of completed threads and new events.

        // It'd be nice to be able to use a drain here, but that causes self-mutable borrowing
        // issues.
        //for mut t in self.active.drain(0..self.active.len()) {
        loop {
            let t = match self.active.pop() {
                Some(t) => t,
                None => {
                    break;
                }
            };
            self.handle_step(t, &mut run_state, &job_status)?;
        }
        if run_state.is_aborted() {
            return run_state.return_abort();
        }

        // Finished processing all the active threads.
        #[cfg(test)]
        assert_eq!(0, self.active.len());

        // Another pass of the new events.
        // This is an edge case that should be handled here.
        for event in run_state.copy_events() {
            self.update_pending_events(&mut run_state, &event)?;
        }

        // Loop through the 'advance' threads to check if any have come to an end.
        // If they've come to an end, then put them in the 'completed_threads' list, else
        // put them in the active list.
        let mut completed_threads = Vec::new();
        let (mut advance, new_jobs, new_events) = run_state.close();

        let mut active_main = 0;
        for mut tpair in advance.drain(0..advance.len()) {
            if tpair.0.advance(tpair.1) {
                completed_threads.push(tpair.0);
            } else {
                if tpair.0.is_main {
                    active_main += 1;
                }
                self.active.push(tpair.0);
            }
        }

        // For each completed thread, put it in the stopped list,
        // and update the waiting-on-thread-stop threads.  Those will also step, which can potentially
        // also update the other waiting-on-thread-stop threads.
        while !completed_threads.is_empty() {
            let mut run_state = AdvanceState::new();
            for t in completed_threads.drain(0..completed_threads.len()) {
                // Check if there's waiting-on.  If so, advance them.
                // If their advance ended it, then add it to the new_completed list.
                let t_ref = t.t_ref;
                let exit = t.get_last_wait();
                if t.is_main {
                    self.main_complete
                        .add(&exit.clone().unwrap_or(DEFAULT_EXIT.clone()));
                }
                self.stopped.insert(t.t_ref, t);

                for pending in self.pending_thread_end.handle(t_ref) {
                    let exit = exit.clone();
                    let (_pt_ref, exit_behavior) = pending.wait_for_thread_step()?;
                    #[cfg(test)]
                    assert_eq!(_pt_ref, t_ref);
                    self.handle_exit_behavior(
                        pending,
                        &exit_behavior,
                        &mut run_state,
                        exit.as_ref(),
                    )?;
                }
            }
            if run_state.is_aborted() {
                return run_state.return_abort();
            }
            for mut tpair in run_state.close().0 {
                if tpair.0.advance(tpair.1) {
                    completed_threads.push(tpair.0);
                } else {
                    if tpair.0.is_main {
                        active_main += 1;
                    }
                    self.active.push(tpair.0);
                }
            }
        }

        // Based on the main thread count, return the loop state.
        if active_main == 0 {
            Ok(Response {
                state: LoopState::Stopped(self.main_complete.clone().close()),
                generated_events: Vec::new(),
                spawned_jobs: Vec::new(),
            })
        } else {
            Ok(Response {
                state: LoopState::Active,
                generated_events: new_events,
                spawned_jobs: new_jobs,
            })
        }
    }

    /// Update the pending_events list based on the encountered event.
    /// Returns the threads that are no longer pending and can be advanced, along with their step count.
    fn update_pending_events(
        &mut self,
        advance: &mut AdvanceState,
        event: &Event,
    ) -> Result<(), String> {
        let mut new_pending = Vec::new();

        let mut tl = self.pending_event.handle(event.0);
        for t in tl.drain(0..tl.len()) {
            let (_w_ref, w_op) = t.wait_for_event_step()?;
            #[cfg(test)]
            assert_eq!(event.0, _w_ref);

            match w_op {
                None => {
                    // Payload doesn't matter, so this is a match.
                    advance.advance_by(t, 1);
                }
                Some(w_p) if w_p == event.1 => {
                    // Payload matches.
                    advance.advance_by(t, 1);
                }
                Some(_) => {
                    new_pending.push(t);
                }
            }
        }

        if !new_pending.is_empty() {
            self.pending_event.replace(event.0, new_pending);
        }

        Ok(())
    }

    fn handle_step<T: JobStatus>(
        &mut self,
        t: ThreadState,
        advance: &mut AdvanceState,
        job_status: &T,
    ) -> Result<(), String> {
        let step = t.step_clone().ok_or(format!(
            "BUG left thread {} in active state when it's completed",
            t.thread.source
        ))?;
        match &step {
            ScheduleStep::Noop => {
                // Do nothing.  Just advance one click.
                advance.advance_by(t, 1);
                Ok(())
            }
            ScheduleStep::SendEvent(event_ref, event_payload) => {
                // Mark the event as something new.
                advance.add_event(event_ref, event_payload);

                // Advance by a click.
                advance.advance_by(t, 1);
                Ok(())
            }
            ScheduleStep::WaitForEvent(e_ref, _) => {
                // Move this into the waiting pile.
                self.pending_event.insert(*e_ref, t);
                Ok(())
            }
            ScheduleStep::SpawnJob(job_ref) => {
                // Mark the job as something new.
                advance.add_job(*job_ref);

                // Advance by a click.
                advance.advance_by(t, 1);
                Ok(())
            }
            ScheduleStep::WaitForJob(job_ref, exit_behavior) => {
                // Can't just immediately wait for the job.  Its state needs to be inspected.
                // Similar to the wait-for-event, this doesn't check the pending job spawns for this step.
                match job_status.job_status(*job_ref) {
                    JobRunStatus::NotExist => Err(format!("no such job {}", job_ref)),
                    JobRunStatus::NeverStarted => {
                        // The exit behavior handles the advance.
                        self.handle_exit_behavior(t, exit_behavior, advance, None);
                        Ok(())
                    }
                    JobRunStatus::Running => {
                        // Put the thread into the pending job wait list.
                        self.pending_job_end.insert(*job_ref, t);
                        Ok(())
                    }
                    JobRunStatus::Stopped(script_exit) => {
                        // The exit behavior handles the advance.
                        self.handle_exit_behavior(t, exit_behavior, advance, Some(&script_exit));
                        Ok(())
                    }
                }
            }
            ScheduleStep::SpawnThread(thread_ref) => {
                // If the thread is in the stopped list, then move it into active.
                if let Some(mut other) = self.stopped.remove(thread_ref) {
                    other.restart();
                    advance.advance_by(other, 0);
                }
                // In either case, advance the thread.
                advance.advance_by(t, 1);
                Ok(())
            }
            ScheduleStep::WaitForThread(thread_ref, exit_behavior) => {
                if let Some(stopped) = self.stopped.get(thread_ref) {
                    // Already stopped, so perform the check behavior.
                    // The exit behavior handles the advance.
                    self.handle_exit_behavior(
                        t,
                        exit_behavior,
                        advance,
                        stopped.get_last_wait().as_ref(),
                    );
                    Ok(())
                } else {
                    // Move the thread into the waiting-on-thread-end list.
                    self.pending_thread_end.insert(*thread_ref, t);
                    Ok(())
                }
            }
            ScheduleStep::WaitForAll(jobs, threads, exit_behavior) => {
                // The complex behavior.
                let acc = WaitAccumulator::new(
                    t,
                    &jobs,
                    &threads,
                    &exit_behavior,
                    |jr| job_status.job_status(*jr),
                    |tr| match self.stopped.get(tr) {
                        None => AccRunStatus::Running,
                        Some(e) => match e.get_last_wait() {
                            None => AccRunStatus::NeverStarted,
                            Some(e) => AccRunStatus::Stopped(e.clone()),
                        },
                    },
                );
                if acc.is_ready() {
                    // Turn this into an exit behavior check.
                    let (t, exit) = acc.close();
                    // The exit behavior handles the advance.
                    self.handle_exit_behavior(t, exit_behavior, advance, Some(&exit));
                    Ok(())
                } else {
                    // Put into the wait-on-many list.
                    self.pending_join.push(acc);
                    Ok(())
                }
            }
        }
    }

    fn handle_exit_behavior(
        &mut self,
        mut t: ThreadState,
        exit_behavior: &ExitBehavior,
        advance: &mut AdvanceState,
        exit: Option<&ScriptExit>,
    ) -> Result<(), String> {
        t.set_last_wait(exit);
        match exit_behavior.behavior_for(match exit {
            None => None,
            Some(e) => Some(e.code),
        }) {
            OnExitBehavior::JumpBy(count) => {
                advance.advance_by(t, count);
                Ok(())
            }
            OnExitBehavior::StopThread(script_exit) => {
                t.stop_thread(script_exit);

                // Put it in the advance list, so that proper thread stop waits are handled.
                advance.advance_by(t, 0);

                Ok(())
            }
            OnExitBehavior::AbortScript(script_exit) => {
                advance.abort(t.get_last_wait(), script_exit);
                // Note: losing track of the thread state object.  That's fine on abort.
                Ok(())
            }
        }
    }
}

const DEFAULT_EXIT: ScriptExit = ScriptExit {
    code: ExitCode::MIN,
    message: None,
};

struct AdvanceState {
    advance: Vec<(ThreadState, StepCount)>,
    abort_exit: Option<ScriptExit>,
    new_jobs: Vec<JobRef>,
    new_events: Vec<Event>,
}

impl AdvanceState {
    pub fn new() -> Self {
        Self {
            advance: Vec::new(),
            abort_exit: None,
            new_jobs: Vec::new(),
            new_events: Vec::new(),
        }
    }

    pub fn is_aborted(&self) -> bool {
        self.abort_exit.is_some()
    }

    pub fn return_abort(self) -> Result<Response, String> {
        match self.abort_exit {
            None => panic!("BUG did not test with is_aborted()"),
            Some(e) => Ok(Response {
                state: LoopState::Stopped(e),
                generated_events: Vec::new(),
                spawned_jobs: Vec::new(),
            }),
        }
    }

    pub fn close(self) -> (Vec<(ThreadState, StepCount)>, Vec<JobRef>, Vec<Event>) {
        (self.advance, self.new_jobs, self.new_events)
    }

    pub fn advance_by(&mut self, t: ThreadState, c: StepCount) {
        self.advance.push((t, c));
    }

    pub fn abort(&mut self, last_exit: Option<ScriptExit>, script_exit: Option<ScriptExit>) {
        self.abort_exit = Some(last_exit.unwrap_or(script_exit.unwrap_or(DEFAULT_EXIT.clone())));
    }

    pub fn add_job(&mut self, job_ref: JobRef) {
        self.new_jobs.push(job_ref);
    }

    pub fn add_event(&mut self, event_ref: &EventRef, payload: &EventPayload) {
        self.new_events.push((*event_ref, payload.clone()));
    }

    pub fn copy_events(&self) -> Vec<Event> {
        self.new_events.clone()
    }
}

/// Maintain an active thread's state.
struct ThreadState {
    t_ref: ThreadRef,

    /// Is this a primary thread that, when complete, shuts down the loop?
    is_main: bool,

    /// The last step wait status, or a possible abort/stop step status.
    x_last_wait: Option<ScriptExit>,

    /// Current place in the thread's steps.
    step_pos: usize,

    /// The reference to the thread.
    thread: ThreadDescription,
}

impl ThreadState {
    pub fn new(t_ref: ThreadRef, thread: ThreadDescription, is_main: bool) -> Self {
        Self {
            t_ref,
            is_main,
            x_last_wait: None,
            step_pos: 0,
            thread,
        }
    }

    pub fn step_clone(&self) -> Option<ScheduleStep> {
        match self.step() {
            None => None,
            Some(e) => Some(e.clone()),
        }
    }

    pub fn step(&self) -> Option<&ScheduleStep> {
        self.thread.steps.get(self.step_pos)
    }

    pub fn get_last_wait(&self) -> Option<ScriptExit> {
        self.x_last_wait.clone()
    }

    pub fn set_last_wait(&mut self, exit: Option<&ScriptExit>) {
        self.x_last_wait = match exit {
            None => None,
            Some(e) => Some(e.clone()),
        };
    }

    pub fn last_wait_code(&self) -> Option<ExitCode> {
        match &self.x_last_wait {
            Some(c) => Some(c.code),
            None => None,
        }
    }

    pub fn wait_for_event_step(&self) -> Result<(EventRef, Option<EventPayload>), String> {
        let step = self.step();
        if let Some(ScheduleStep::WaitForEvent(w_ref, w_op)) = step {
            Ok((*w_ref, w_op.clone()))
        } else {
            Err(format!(
                "BUG expected wait-for-event step, found {:?}",
                step
            ))
        }
    }

    pub fn wait_for_job_step(&self) -> Result<(JobRef, ExitBehavior), String> {
        let step = self.step();
        if let Some(ScheduleStep::WaitForJob(j_ref, jb)) = step {
            Ok((*j_ref, jb.clone()))
        } else {
            Err(format!("BUG expected wait-for-job step, found {:?}", step))
        }
    }

    pub fn wait_for_thread_step(&self) -> Result<(ThreadRef, ExitBehavior), String> {
        let step = self.step();
        if let Some(ScheduleStep::WaitForThread(t_ref, tb)) = step {
            Ok((*t_ref, tb.clone()))
        } else {
            Err(format!(
                "BUG expected wait-for-thread step, found {:?}",
                step
            ))
        }
    }

    /// Advance by the given count.  Returns 'true' if it's come to an end.
    pub fn advance(&mut self, count: StepCount) -> bool {
        if count == 0 {
            true
        } else {
            let next = i32::try_from(self.step_pos).expect("bad step position") + i32::from(count);
            if next < 0 {
                self.step_pos = 0;
                false
            } else {
                let next = usize::try_from(next).expect("bad step position");
                if next >= self.thread.steps.len() {
                    self.step_pos = self.thread.steps.len();
                    true
                } else {
                    self.step_pos = next;
                    false
                }
            }
        }
    }

    /// The final exit code will be the job's exit code, or `ExitCode::MIN` if the job has never started.
    /// If the error is given and the job did not error, then the thread stops with this error.
    pub fn stop_thread(&mut self, exit: Option<ScriptExit>) {
        if self.x_last_wait.is_none() {
            self.x_last_wait = match exit {
                Some(_) => exit,
                None => Some(DEFAULT_EXIT.clone()),
            };
        }
        self.step_pos = self.thread.steps.len();
    }

    /// Restarts the thread.
    /// If it was a main thread, it won't be counted as one after this.
    pub fn restart(&mut self) {
        self.step_pos = 0;
        self.is_main = false;
    }
}

/// Manages the state of a thread that's on a "WaitAll" step.
struct WaitAccumulator {
    thread: ThreadState,
    jobs_ready_count: usize,
    threads_ready_count: usize,
    jobs: HashMap<JobRef, AccRunStatus>,
    threads: HashMap<ThreadRef, AccRunStatus>,
    on_complete: ExitBehavior,
}

enum AccRunStatus {
    NeverStarted,
    Running,
    Stopped(ScriptExit),
}

impl AccRunStatus {
    pub fn is_running(&self) -> bool {
        match self {
            AccRunStatus::Running => true,
            _ => false,
        }
    }
}

impl WaitAccumulator {
    pub fn new<A, B>(
        thread: ThreadState,
        jobs: &Vec<JobRef>,
        threads: &Vec<ThreadRef>,
        on_complete: &ExitBehavior,
        check_job: A,
        check_thread: B,
    ) -> Self
    where
        A: Fn(&JobRef) -> JobRunStatus,
        B: Fn(&ThreadRef) -> AccRunStatus,
    {
        let mut hj = HashMap::new();
        let mut jobs_ready_count = 0;
        for j in jobs {
            let res = match check_job(j) {
                JobRunStatus::NotExist | JobRunStatus::NeverStarted => {
                    jobs_ready_count += 1;
                    AccRunStatus::NeverStarted
                }
                JobRunStatus::Running => AccRunStatus::Running,
                JobRunStatus::Stopped(script_exit) => {
                    jobs_ready_count += 1;
                    AccRunStatus::Stopped(script_exit)
                }
            };
            hj.insert(*j, res);
        }
        let mut ht = HashMap::new();
        let mut threads_ready_count = 0;
        for t in threads {
            let res = check_thread(t);
            threads_ready_count += match &res {
                AccRunStatus::NeverStarted | AccRunStatus::Stopped(_) => 1,
                AccRunStatus::Running => 0,
            };
            ht.insert(*t, res);
        }
        Self {
            thread,
            jobs_ready_count,
            threads_ready_count,
            jobs: hj,
            threads: ht,
            on_complete: on_complete.clone(),
        }
    }

    pub fn requires_job(&self, j_ref: JobRef) -> bool {
        self.jobs.contains_key(&j_ref)
    }

    pub fn is_ready(&self) -> bool {
        self.jobs_ready_count == self.jobs.len() && self.threads_ready_count == self.threads.len()
    }

    /// Close off this accumulator.  Only call if is_ready() returns true.
    pub fn close(self) -> (ThreadState, ScriptExit) {
        if !self.is_ready() {
            panic!("BUG bad ready state");
        }
        let mut coll = ErrCollector::new();
        for oe in self.jobs.values() {
            match oe {
                AccRunStatus::Running => panic!("BUG jobs_ready_count"),
                AccRunStatus::NeverStarted => (),
                AccRunStatus::Stopped(e) => coll.add(e),
            }
        }
        for oe in self.threads.values() {
            match oe {
                AccRunStatus::Running => panic!("BUG threads_ready_count"),
                AccRunStatus::NeverStarted => (),
                AccRunStatus::Stopped(e) => coll.add(e),
            };
        }

        (self.thread, coll.close())
    }

    pub fn on_job_exit(&mut self, j_ref: JobRef, exit: ScriptExit) -> bool {
        #[cfg(test)]
        let len = self.jobs.len();

        if let Some(oj) = self.jobs.get(&j_ref) {
            if oj.is_running() {
                // Not set yet, so we have a ready job.
                self.jobs_ready_count += 1;

                #[cfg(test)]
                assert!(self.jobs_ready_count <= len);
            }
            self.jobs.insert(j_ref, AccRunStatus::Stopped(exit));
        }
        self.is_ready()
    }

    pub fn on_thread_exit(&mut self, t_ref: ThreadRef, exit: ScriptExit) -> bool {
        #[cfg(test)]
        let len = self.threads.len();

        if let Some(oj) = self.threads.get(&t_ref) {
            if oj.is_running() {
                // Not set yet, so we have a ready thread.
                self.threads_ready_count += 1;

                #[cfg(test)]
                assert!(self.threads_ready_count <= len);
            }
            self.threads.insert(t_ref, AccRunStatus::Stopped(exit));
        }
        self.is_ready()
    }
}

#[derive(Clone)]
struct ErrCollector {
    first: bool,
    msg: String,
    err_count: ExitCode,
    pub total: usize,
}

impl ErrCollector {
    pub fn new() -> Self {
        Self {
            first: true,
            msg: String::new(),
            err_count: 0,
            total: 0,
        }
    }

    pub fn add(&mut self, exit: &ScriptExit) {
        self.total += 1;
        if let Some(message) = &exit.message {
            if self.first {
                self.first = false;
            } else {
                self.msg.push('\n');
            }
            self.msg.push_str(message.as_str());
        }
        if exit.code != 0 {
            self.err_count += 1;
        }
    }

    pub fn close(self) -> ScriptExit {
        if self.first {
            // No messages added.
            ScriptExit {
                code: self.err_count,
                message: None,
            }
        } else {
            ScriptExit {
                code: self.err_count,
                message: Some(self.msg),
            }
        }
    }
}
