// Under the MIT License.  See LICENSE file for details.

package templates

import "github.com/groboclown/native-shell/nativeshell/ast"

// ShellTemplate describes a snippet of the code to insert as the native code.
//
// The Code matches up with the "text/template" package format.
// The Code must reference the GlobalField and ContextField names as {.name} Key references.
type ShellTemplate struct {
	Name           string
	Source         ast.Source
	Code           string
	ParameterTypes map[string]ParameterType
	GlobalFields   map[string]FieldType
	ContextFields  map[string]FieldType
}

// ParameterType describes a user entry to fill a value in a shell template.
//
// Parameters may also be connected to fields.
type ParameterType struct {
	FieldType
}

type FieldTypeId int

const (
	FieldTypeString FieldTypeId = iota
	FieldTypeBool
	FieldTypeInt
	FieldTypeFloat
)

// FieldType describes a value field generated by the shell template.
type FieldType struct {
	IsArray bool
	Type    FieldTypeId
}
